### ISSUE TITLE
Welcome Scene

### ISSUE THREAD

**Issue by unoctium1** [ubcemergingmedialab/able-tools#2]
Scenes:
————
An official EML "welcome to VR" tutorial

From watching some new users at the Showcase and in drop-ins, I think there are some easy things we could do to improve the new user experience so people can prep in about 5 minutes before jumping into our projects.

This is a big project! Fortunately, there are some quick and easy things we can do: mimic the Oculus experience to highlight buttons on the controller when they're pressed, write a list of best practices we can follow when making new VR experiences, and so on.

We'll need to think through some features that would make it easier for new users to figure out what they're doing when they enter VR. There could even be a recorded voiceover, but these are all features that can be added.

What should it look like? Let's decide. A forest? A grassy field? Someone's apartment?

Idea by: @catherineomega 

Note: We'll probably want to break this up into multiple tools and tasks. This also fits more into the SampleAssets section than tools

**Comment by sandyklc** [comment]
Things Discussed on October 16, 2019:
1. List of best practices: a set of guidelines for universal controls for VR controllers in the laboratory (ex, use joystick for moving etc), set of user research guidelines to do before starting a project, best practices for application on-boarding (adequate amount of instructions and signifiers to help the users know how to use the controls)
2. Brainstorm on the layout of the Welcome scene
- Could be a house/apartment you enter, and each room will have its own theme and tutorial purpose (1 will be forest, 1 will be room etc etc)
3. Watch and observe new users in the IKB space drop-ins to get new-to-VR-user behaviours.
